application: routeticker-api
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: helloworld_api.APPLICATION

- url: /bootstrap
  script: bootstrap.application

- url: /login
  script: bootstrap.application

- url: /clear
  script: bootstrap.application

- url: /test
  script: test_runner.application

- url: /.*
  script: helloworld.application

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
